services:
    text-encoders-devcontainer:
        network_mode: host
        image: text-encoders-devcontainer
        container_name: text-encoders-devcontainer
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
            ssh:
                - default
            args:
                - PYTHON_VERSION
                - PIP_VERSION
                - DEVCONTAINER_USER
        volumes:
            - ..:/workspace:cached
            - ../resources/:/resources
        env_file:
            - ../.secrets/.env
        # This keeps the devcontainer running.
        entrypoint: [ "tail", "-f", "/dev/null" ]

    text-encoders-weaviate:
        image: semitechnologies/weaviate:${WEAVIATE_VERSION}
        container_name: text-encoders-weaviate
        network_mode: host
        command:
            - --host
            - 0.0.0.0
            - --port
            - "8181"
            - --scheme
            - http
        volumes:
            - $PWD/resources/db/weaviate:/resources/weaviate
        environment:
            QUERY_DEFAULTS_LIMIT: 25
            AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
            PERSISTENCE_DATA_PATH: '/resources/weaviate'
            DEFAULT_VECTORIZER_MODULE: 'none'
            ENABLE_MODULES: ''
            AUTOSCHEMA_ENABLED: 'false'
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 512M
